export const reviewEvents = [
  {
    id: '500243202604110001',
    title: '高谷镇G319国道2270处公路岩质边坡垮塌',
    type: '崩塌',
    scale: '小型',
    level: '较大',
    riskLevelValue: 3,
    status: '已处置',
    reviewStatus: '待复盘',
    source: '专业监测预警',
    time: '2026-04-11 16:35:08',
    location: '彭水县高谷镇陈家村6组',
    district: '彭水苗族土家族自治县',
    coordinate: '108.1668, 29.2936',
    cause: '降雨、道路切坡、风化剥蚀',
    description: '公路岩质边坡发生垮塌，调查时造成G319国道交通中断；无人员伤亡；已采取警戒、交通管制并组织清障。',
    stableStatus: '—',
    timeType: '新生突变',
    hazardName: '—',
    susceptibility: '中易发区',
    riskArea: '中风险区',
    populationBase: '新生突变',
    threatObject: '公路交通',
    threatTarget: '公路交通设施',
    casualties: '0人',
    evacuatedHouseholds: '0户',
    evacuatedPeople: '0人',
    injuredCount: '0人',
    missingCount: '0人',
    deathCount: '0人',
    economicLoss: '2万元',
    materials: '基础信息、图片、调查报告已关联',
    materialLinks: [
      { label: '图片资料(2)', type: 'images', count: 2 },
      { label: '调查报告', type: 'report' },
    ],
    timeline: [
      {
        step: '1.险情上报',
        title: '险情上报',
        content: '上报G319国道2270处公路岩质边坡垮塌。',
        operatorRole: '上报人',
        operator: '张三',
        time: '2026-06-05 09:12',
        alert: '调查报告记载时间为16:30，请核对。',
      },
      {
        step: '2.现场调查任务派发',
        title: '现场调查任务派发',
        content: '通知驻守现场地质工程师会同高谷镇政府工作人员一起开展现场调查。',
        operatorRole: '操作人',
        operator: '里斯',
        time: '2026-06-05 09:12',
      },
      {
        step: '3.现场调查反馈',
        title: '现场调查反馈',
        content: '现场确认灾岩顺向坡、裂隙发育，垮塌体约25m³；道路交通中断，无人员伤亡。',
        operatorRole: '反馈人',
        operator: '驻守地质工程师',
        time: '2026-06-05 09:12',
        photos: [
          new URL('@/assets/imgs/fupan/site-photo-1.png', import.meta.url).href,
          new URL('@/assets/imgs/fupan/site-photo-2.png', import.meta.url).href,
        ],
        summary: '已完成踏勘，并设置警戒并临时管制交通，组织清除路面堆积体。',
        siteLocation: '高谷镇陈家村6组G319国道270处',
      },
      {
        step: '4.调查报告生成',
        title: '调查报告生成',
        content: '已形成《高谷镇G319国道2270处内侧边坡垮塌调查报告》',
        operatorRole: '操作人',
        operator: '张三',
        time: '2026-06-05 09:12',
      },
      {
        step: '5.后续处置与归档',
        title: '后续处置与归档',
        content: '清除、治理、恢复通行及归档结果待补充。',
        operatorRole: '操作人',
        operator: '李四',
        time: '2026-06-05 14:30',
      },
    ],
  },
  {
    id: '500243202604090016',
    title: '郁山镇米阳坝村3组滑坡变形事件',
    type: '滑坡',
    scale: '小型',
    level: '一般',
    riskLevelValue: 2,
    status: '跟踪中',
    reviewStatus: '待复盘',
    source: '群测群防上报',
    time: '2026-06-04 16:48:22',
    location: '彭水县郁山镇米阳坝村3组',
    district: '彭水苗族土家族自治县',
    coordinate: '108.4932, 29.5358',
    cause: '降雨冲刷、坡脚开挖',
    description: '巡查发现滑坡后缘裂缝较前期有所扩展，暂未影响周边居民，已安排专人持续跟踪。',
    stableStatus: '基本稳定',
    timeType: '既有变形',
    hazardName: '米阳坝滑坡隐患点',
    susceptibility: '低易发区',
    riskArea: '中风险区',
    populationBase: '8人',
    threatObject: '村民住宅',
    threatTarget: '村民住宅及村道',
    casualties: '0人',
    evacuatedHouseholds: '0户',
    evacuatedPeople: '0人',
    injuredCount: '0人',
    missingCount: '0人',
    deathCount: '0人',
    economicLoss: '0万元',
    materials: '基础信息、现场照片已关联',
    materialLinks: [
      { label: '图片资料(1)', type: 'images', count: 1 },
      { label: '核查记录', type: 'report' },
    ],
    timeline: [
      {
        step: '1.险情上报',
        title: '群测群防员上报',
        content: '巡查发现后缘裂缝扩展并上传现场照片。',
        operatorRole: '上报人',
        operator: '王五',
        time: '2026-06-04 16:48',
      },
      {
        step: '2.事件核验',
        title: '事件信息完成核验',
        content: '属地自然资源所确认上报信息有效。',
        operatorRole: '审核人',
        operator: '所长赵六',
        time: '2026-06-04 17:02',
      },
      {
        step: '3.现场调查',
        title: '技术人员现场调查',
        content: '完成裂缝测量并新增两处简易监测点。',
        operatorRole: '调查人',
        operator: '工程师孙工',
        time: '2026-06-04 17:35',
      },
      {
        step: '4.持续跟踪',
        title: '转入持续跟踪',
        content: '安排专人每日巡查，降雨期间加密监测频次。',
        operatorRole: '操作人',
        operator: '网格员周七',
        time: '2026-06-04 18:10',
      },
    ],
  },
  {
    id: '500243202604080008',
    title: '绍庆街道临江社区危岩落石事件',
    type: '危岩',
    scale: '小型',
    level: '较大',
    riskLevelValue: 3,
    status: '已处置',
    reviewStatus: '已复盘',
    source: '群众上报',
    time: '2026-06-03 11:20:15',
    location: '彭水县绍庆街道临江社区',
    district: '彭水苗族土家族自治县',
    coordinate: '108.1783, 29.2871',
    cause: '风化剥蚀、岩体自重破坏',
    description: '临江社区后山出现小规模落石，现场无人员伤亡，受威胁区域人员已转移避险。',
    stableStatus: '相对稳定',
    timeType: '新生突发',
    hazardName: '临江社区危岩带',
    susceptibility: '高易发区',
    riskArea: '高风险区',
    populationBase: '12人',
    threatObject: '居民楼',
    threatTarget: '社区居民楼及道路',
    casualties: '0人',
    evacuatedHouseholds: '4户',
    evacuatedPeople: '12人',
    injuredCount: '0人',
    missingCount: '0人',
    deathCount: '0人',
    economicLoss: '5万元',
    materials: '基础信息、处置记录已关联',
    materialLinks: [
      { label: '图片资料(3)', type: 'images', count: 3 },
      { label: '排危报告', type: 'report' },
    ],
    timeline: [
      {
        step: '1.群众上报',
        title: '群众电话上报',
        content: '社区收到居民关于后山落石的报告。',
        operatorRole: '记录人',
        operator: '社区前台',
        time: '2026-06-03 11:20',
      },
      {
        step: '2.避险转移',
        title: '人员临时转移',
        content: '受威胁区域居民转移至社区临时安置点。',
        operatorRole: '组织人',
        operator: '社区网格组',
        time: '2026-06-03 11:32',
      },
      {
        step: '3.排危处置',
        title: '排危作业开始',
        content: '专业队伍清除松动岩块并设置防护网。',
        operatorRole: '处置队',
        operator: '应急抢险队',
        time: '2026-06-03 12:15',
      },
      {
        step: '4.风险解除',
        title: '风险复核与解除',
        content: '专家复核确认现场已达到安全条件。',
        operatorRole: '专家',
        operator: '地质专家组',
        time: '2026-06-03 17:40',
      },
    ],
  },
  {
    id: '500243202604020031',
    title: '保家镇鹿山社区道路边坡异常事件',
    type: '滑坡',
    scale: '小型',
    level: '一般',
    riskLevelValue: 1,
    status: '已归档',
    reviewStatus: '已复盘',
    source: '智能识别',
    time: '2026-06-02 08:36:40',
    location: '彭水县保家镇鹿山社区',
    district: '彭水苗族土家族自治县',
    coordinate: '108.3280, 29.4175',
    cause: '道路开挖、降雨软化',
    description: '遥感变化识别发现道路边坡存在新增裸露区域，经现场核实未发生明显变形。',
    stableStatus: '稳定',
    timeType: '排查发现',
    hazardName: '鹿山边坡',
    susceptibility: '低易发区',
    riskArea: '低风险区',
    populationBase: '0人',
    threatObject: '机耕道',
    threatTarget: '农村机耕道',
    casualties: '0人',
    evacuatedHouseholds: '0户',
    evacuatedPeople: '0人',
    injuredCount: '0人',
    missingCount: '0人',
    deathCount: '0人',
    economicLoss: '0万元',
    materials: '基础信息、现场核查记录已关联',
    materialLinks: [
      { label: '图片资料(1)', type: 'images', count: 1 },
      { label: '核查报告', type: 'report' },
    ],
    timeline: [
      {
        step: '1.智能识别',
        title: '智能识别发现异常',
        content: '变化检测模型识别到新增裸露区域。',
        operatorRole: '系统',
        operator: 'AI识别服务',
        time: '2026-06-02 08:36',
      },
      {
        step: '2.现场核查',
        title: '现场核查完成',
        content: '确认裸露区域为道路施工形成，无明显变形迹象。',
        operatorRole: '核查人',
        operator: '片区督查员',
        time: '2026-06-02 10:20',
      },
      {
        step: '3.归档结案',
        title: '事件归档',
        content: '补充现场资料后完成事件归档。',
        operatorRole: '归档人',
        operator: '档案管理员',
        time: '2026-06-02 11:05',
      },
    ],
  },
]

export const reviewTypeOptions = ['全部事件', '崩塌', '滑坡', '危岩']
